
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  # H2database 驱动
  driver-class-name: org.h2.Driver
  url: jdbc:h2:file:~/taco/taco
  username: wollo
  password: 123456
h2:
  console:
    settings:
      web-allow-others: false
    path: /taco/taco
    enabled: true
#server:
#  port: 8044